# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Murgia's Blog
email: matthew.murgia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Matthew Murgia and I am a developer that loves to get out of my comfort zone to learn and help others.  I have a background in sustainability and enjoy finding solutions to problems that have the capacity to endure. This is my blog to help explain new concepts for beginners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://murgia.github.io/D3-blog-post/" # the base hostname & protocol for your site
github_username:  murgia

# Build settings
markdown: kramdown


safe: true
lsi: false
source: d3-blog-post
